### ISSUE TITLE
Allow insecure ciphers

### ISSUE THREAD

**Issue by ghost** [ronomon/crypto-async#15]
Hello.

We're using RC4 from the native crypto module at this moment for non-critical data ciphering. I was excited to upgrade this part of our solution with an async library, but to my surprise I got greeted with a message that told me this algorithm is disabled.

In my opinion, weak ciphers **should** be allowed as they're even native to Node. Any future plans for allowing this? Perhaps some sort of option? It's a real bummer!

**Comment by jorangreef** [comment]
Thanks @Zaseth , I'm sorry that the lack of RC4 is a blocker for you, but RC4 is not something this module would support. The limited surface area is a feature not a bug!
