### ISSUE TITLE
Current support

### ISSUE THREAD

**Issue by Kylar13** [ronomon/crypto-async#16]
Hi there,

I was wondering if there's any current support for this library and whether the problems it tries to solve still exist in NodeJS 14.x.

I don't want to introduce and event loop blocker on the API I'm working on, but I don't see any signs of current support and/or security updates for this module and that worries me.

**Comment by jorangreef** [comment]
Hi @Kylar13 feel free to open an issue (and PR) if the tests are not working. The tests are fairly exhaustive fuzz tests that fuzz the positive and negative space.
