### ISSUE TITLE
How to easily use this package？

### ISSUE THREAD

**Issue by vincentLiuxiang** [ronomon/crypto-async#2]
hi @jorangreef how can i very easily to use this package?

when i use node.js native crypto it is very clear:
```javascript
const crypto = require('crypto');
const hash = crypto.createHash('SHA256');
hash.update('hello world');
console.log('@@',hash.digest('hex'));
```

how can i get the same result via crypto-async?

**Comment by jorangreef** [comment]
Thanks for the feedback @vincentLiuxiang.

Easy-to-use methods have just been added with https://github.com/jorangreef/crypto-async/commit/ab9e605ce66549d97315be069e2dd5f2bd8936f9.

The README has been updated with examples of these new methods.

For example, to hash asynchronously across multiple cores with `crypto-async`:

```javacsript
var cryptoAsync = require('crypto-async');
cryptoAsync.hash('SHA256', new Buffer('hello world'),
  function(error, hash) {
    if (error) throw error;
    console.log(hash.toString('hex'));
  }
);
```

**Comment by vincentLiuxiang** [comment]
thanks @jorangreef
