### ISSUE TITLE
Set engineStrict to true

### ISSUE THREAD

**Issue by skerit** [ronomon/crypto-async#5]
Just a small thing: Because the `engines` property in the `package.json` file is just advisory, npm will install the latest version of `crypto-async` even on older node.js versions.

Adding `"engineStrict": true,` to the package file should help with that a bit.

**Comment by jorangreef** [comment]
Thanks @skerit, good catch.

**Comment by jorangreef** [comment]
Fixed in https://github.com/ronomon/crypto-async/commit/e8d28fc703d8fcca6fbbff1d0f9524a0821c9bd0
